.\" Manpage pour notre projet de MiniSHeLL.
.\" Contact jeanml.still@gmail.com pour plus d'information.
.TH man "20/03/2018" "1.0" "Shell man page"
.SH NAME
./bin/MiniSHeLL \- Permet de lancer un shell "maison"
.SH SYNOPSIS
 : ./bin/MiniSHeLL
.SH DESCRIPTION
Shell développé dans le cadre du CNAM pour le cours de Système d'Exploitation Avancé de 2ème année
.SH OPTIONS
 -b permet de lancer le shell en mode batch (ex : ./bin/MiniSHeLL -b ls -l) 
.SH SEE ALSO
man bash
.SH BUGS
No known bugs.
.SH AUTHOR
Loïc Bine & Jean Still
