.\" Manpage pour notre projet de MiniSHeLL.
.\" Contact jeanml.still@gmail.com pour plus d'information.
.TH man "20/03/2018" "1.0" "MiniSHeLL man page"
.SH NAME
./bin/MiniSHeLL \- Permet de lancer le shell du projet
.SH SYNOPSIS
 : ./bin/MiniSHeLL
.SH DESCRIPTION
MiniShell développé dans le cadre du CNAM module Système d'Exploitation Avancé de 2ème année
.SH OPTIONS
 -b permet de lancer le minishell en mode batch (ex : ./bin/MiniSHeLL -c ls -l) 
.SH SEE ALSO
man bash
.SH BUGS
No known bugs.
.SH AUTHOR
Loïc Bine & Jean Still
